//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSViewController.h"

@class NSArray;

@interface CHViewController : NSViewController
{
    CHViewController *_parentViewController;
    NSArray *_childViewControllers;
}

@property(copy, nonatomic) NSArray *childViewControllers; // @synthesize childViewControllers=_childViewControllers;
@property(nonatomic) __weak CHViewController *parentViewController; // @synthesize parentViewController=_parentViewController;
- (void).cxx_destruct;
- (void)setTargetsToNil:(id)arg1;
- (void)dealloc;
- (id)firstResponderAlternativeForLosingFocus;
- (void)viewControllerWillDisappear;
- (id)rootViewController;
- (void)removeChildViewController:(id)arg1;
- (void)addChildViewController:(id)arg1;
- (id)nibName;
- (id)initWithCoder:(id)arg1;
- (id)init;

@end

