//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MSBaseAction.h"

@interface MSBaseShapeAction : MSBaseAction
{
}

+ (id)insertShapeLayer:(id)arg1 identifier:(id)arg2 document:(id)arg3;
- (id)label;
- (id)insertShape;
- (id)shapeForInsertion;
- (void)doPerformAction:(id)arg1;
- (id)tooltip;
- (BOOL)isSelectable;
- (id)recipeName;

@end

