//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSWindow.h"

@interface MSDocumentWindow : NSWindow
{
}

- (BOOL)closePopovers;
- (BOOL)shouldDismissPopover:(id)arg1 event:(id)arg2;
- (void)sendEvent:(id)arg1;

@end

