//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSView.h"

@class MSLayer;

@interface MSLayerPreviewView : NSView
{
    MSLayer *_previewedLayer;
}

@property(retain, nonatomic) MSLayer *previewedLayer; // @synthesize previewedLayer=_previewedLayer;
- (void).cxx_destruct;
- (id)menuForEvent:(id)arg1;
- (void)drawRect:(struct CGRect)arg1;

@end

