//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class MSLayer;

@interface MSLayerListTuple : NSObject
{
    MSLayer *_layer;
    long long _level;
}

+ (id)tupleWithLayer:(id)arg1 level:(long long)arg2;
@property(nonatomic) long long level; // @synthesize level=_level;
@property(retain, nonatomic) MSLayer *layer; // @synthesize layer=_layer;
- (void).cxx_destruct;

@end

