//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSSearchField.h"

@class PXListView;

@interface MSSearchField : NSSearchField
{
    PXListView *_layerListView;
}

@property(nonatomic) __weak PXListView *layerListView; // @synthesize layerListView=_layerListView;
- (void).cxx_destruct;
- (id)textView:(id)arg1 completions:(id)arg2 forPartialWordRange:(struct _NSRange)arg3 indexOfSelectedItem:(long long *)arg4;
- (void)moveFocusToTableView;
- (BOOL)textView:(id)arg1 doCommandBySelector:(SEL)arg2;

@end

