//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"
#import "PXListViewDelegate.h"

@class MSSourceListView, NSEvent, NSIndexSet;

@protocol MSSourceListViewDelegate <NSObject, PXListViewDelegate>
- (BOOL)listView:(MSSourceListView *)arg1 rowIsPartOfSymbol:(unsigned long long)arg2;
- (NSIndexSet *)listView:(MSSourceListView *)arg1 actualSelectionIndexes:(NSIndexSet *)arg2;
- (id)listView:(MSSourceListView *)arg1 menuForEvent:(NSEvent *)arg2;
@end

