//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSDictionary.h"

@interface NSDictionary (MSPluginBundle)
- (id)urlForKey_MS:(id)arg1;
- (id)numberForKey_MS:(id)arg1;
- (id)dictionaryForKey_MS:(id)arg1;
- (id)arrayForKey_MS:(id)arg1;
- (id)stringForKey_MS:(id)arg1;
@end

