//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MSShadowStyleCollection.h"

__attribute__((visibility("hidden")))
@interface MSInnerShadowStyleCollection : MSShadowStyleCollection
{
}

+ (Class)immutableClass;
- (id)stylePartForInserting;

@end

