//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

__attribute__((visibility("hidden")))
@interface SVGTransformImporter : NSObject
{
}

+ (id)matrixTransformFromComponents:(id)arg1;
+ (id)rotateTransformFromComponents:(id)arg1;
+ (id)scaleTransformFromComponents:(id)arg1;
+ (id)translateTransformFromComponents:(id)arg1;
+ (id)transformFromName:(id)arg1 components:(id)arg2;
+ (id)transformFromString:(id)arg1;

@end

